// src/server/db.ts
import { Database } from "bun:sqlite";
import { applyWave8Migration } from "./migrations/wave8";

export function createDatabase(dbPath: string): Database {
  const db = new Database(dbPath, { create: true });
  db.run("PRAGMA journal_mode = WAL");
  db.run("PRAGMA foreign_keys = ON");
  return db;
}

export function initSchema(db: Database): void {
  db.run(`
    CREATE TABLE IF NOT EXISTS notes (
      id INTEGER PRIMARY KEY,
      path TEXT UNIQUE NOT NULL,
      title TEXT,
      content_hash TEXT,
      created TEXT,
      modified TEXT
    )
  `);

  db.run(`
    CREATE VIRTUAL TABLE IF NOT EXISTS notes_fts USING fts5(
      title, content, path
    )
  `);

  db.run(`
    CREATE TABLE IF NOT EXISTS backlinks (
      source_id INTEGER REFERENCES notes(id) ON DELETE CASCADE,
      target_id INTEGER REFERENCES notes(id) ON DELETE CASCADE,
      context TEXT,
      PRIMARY KEY (source_id, target_id)
    )
  `);

  db.run(`
    CREATE TABLE IF NOT EXISTS tags (
      note_id INTEGER REFERENCES notes(id) ON DELETE CASCADE,
      tag TEXT NOT NULL,
      PRIMARY KEY (note_id, tag)
    )
  `);

  // Wave 8: rewrite of graph schema. The legacy integer-keyed graph_edges
  // table is dropped and recreated as a TEXT-keyed table so that non-note
  // nodes (sections, tags, semantic aliases) can be linked alongside notes.
  // Structural edges are regenerated by the indexer on next reindex, so the
  // drop is data-safe.
  const graphEdgeCols = db
    .query("PRAGMA table_info(graph_edges)")
    .all() as { name: string }[];
  const hasLegacyGraphEdges =
    graphEdgeCols.length > 0 &&
    graphEdgeCols.some((c) => c.name === "source_id");
  if (hasLegacyGraphEdges) {
    db.run("DROP TABLE graph_edges");
  }

  db.run(`
    CREATE TABLE IF NOT EXISTS graph_nodes (
      id TEXT PRIMARY KEY,
      kind TEXT NOT NULL CHECK (kind IN ('note','section','tag')),
      note_path TEXT,
      label TEXT,
      community_id INTEGER,
      content_hash TEXT
    )
  `);
  db.run(
    `CREATE INDEX IF NOT EXISTS idx_graph_nodes_note ON graph_nodes(note_path)`,
  );
  db.run(
    `CREATE INDEX IF NOT EXISTS idx_graph_nodes_kind ON graph_nodes(kind)`,
  );

  db.run(`
    CREATE TABLE IF NOT EXISTS graph_edges (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      source TEXT NOT NULL,
      target TEXT NOT NULL,
      relation TEXT NOT NULL,
      weight REAL,
      confidence TEXT,
      reason TEXT,
      client_tag TEXT,
      created_at INTEGER,
      UNIQUE (source, target, relation)
    )
  `);
  db.run(
    `CREATE INDEX IF NOT EXISTS idx_graph_edges_source ON graph_edges(source)`,
  );
  db.run(
    `CREATE INDEX IF NOT EXISTS idx_graph_edges_target ON graph_edges(target)`,
  );
  db.run(
    `CREATE INDEX IF NOT EXISTS idx_graph_edges_relation ON graph_edges(relation)`,
  );

  db.run(`
    CREATE TABLE IF NOT EXISTS tasks (
      id INTEGER PRIMARY KEY,
      note_id INTEGER REFERENCES notes(id) ON DELETE CASCADE,
      text TEXT NOT NULL,
      done INTEGER DEFAULT 0,
      due_date TEXT,
      priority INTEGER DEFAULT 0,
      board TEXT DEFAULT 'backlog',
      line INTEGER DEFAULT 0
    )
  `);

  db.run(`
    CREATE TABLE IF NOT EXISTS aliases (
      note_id INTEGER REFERENCES notes(id) ON DELETE CASCADE,
      alias TEXT NOT NULL,
      PRIMARY KEY (note_id, alias)
    )
  `);

  db.run(`
    CREATE TABLE IF NOT EXISTS csv_cache (
      file_path TEXT PRIMARY KEY,
      headers TEXT,
      row_count INTEGER,
      last_parsed TEXT
    )
  `);

  db.run(`
    CREATE TABLE IF NOT EXISTS metadata (
      key TEXT PRIMARY KEY,
      value TEXT
    )
  `);

  db.run(`
    CREATE TABLE IF NOT EXISTS activity_log (
      id         INTEGER PRIMARY KEY AUTOINCREMENT,
      timestamp  TEXT    NOT NULL,
      action     TEXT    NOT NULL,
      kind       TEXT,
      path       TEXT    NOT NULL,
      actor      TEXT    NOT NULL,
      meta       TEXT
    )
  `);
  db.run(`CREATE INDEX IF NOT EXISTS idx_activity_timestamp ON activity_log(timestamp DESC)`);
  db.run(`CREATE INDEX IF NOT EXISTS idx_activity_actor ON activity_log(actor, timestamp DESC)`);
  db.run(`CREATE INDEX IF NOT EXISTS idx_activity_kind ON activity_log(kind, timestamp DESC)`);

  db.run(`
    CREATE TABLE IF NOT EXISTS research_runs (
      id            INTEGER PRIMARY KEY AUTOINCREMENT,
      thread_slug   TEXT    NOT NULL,
      note_path     TEXT    NOT NULL,
      status        TEXT    NOT NULL,
      started_at    TEXT    NOT NULL,
      completed_at  TEXT,
      duration_ms   INTEGER,
      model         TEXT,
      tokens_in     INTEGER,
      tokens_out    INTEGER,
      error         TEXT
    )
  `);
  db.run(`CREATE INDEX IF NOT EXISTS idx_runs_thread ON research_runs(thread_slug, started_at DESC)`);
  db.run(`CREATE INDEX IF NOT EXISTS idx_runs_status ON research_runs(status, started_at DESC)`);

  db.exec(`
    CREATE TABLE IF NOT EXISTS link_index (
      slug TEXT NOT NULL,
      path TEXT NOT NULL,
      title TEXT,
      PRIMARY KEY (slug, path)
    );
    CREATE INDEX IF NOT EXISTS link_index_slug_idx ON link_index (slug);
  `);

  // Additive migration: notes.domain / subdomain / tags were introduced in
  // Wave 7 for the domain-aware graph. Older DBs may not have them, so add
  // each column only when PRAGMA table_info confirms it's missing.
  const noteCols = db
    .query("PRAGMA table_info(notes)")
    .all() as { name: string }[];
  const have = new Set(noteCols.map((c) => c.name));
  if (!have.has("domain")) db.run("ALTER TABLE notes ADD COLUMN domain TEXT");
  if (!have.has("subdomain"))
    db.run("ALTER TABLE notes ADD COLUMN subdomain TEXT");
  if (!have.has("tags")) db.run("ALTER TABLE notes ADD COLUMN tags TEXT");

  // Wave 8: note_metadata, note_sections, note_chunk_embeddings, mcp_dedup.
  applyWave8Migration(db);
}
