// tests/sync/sync-recalibration.test.ts
//
// End-to-end sync-recalibration integration test (Task 35).
//
// Proves that after a simulated pull (writing vault bytes + reindexing), the
// full recalibration pipeline fires correctly:
//   C1 – contextual embeddings written to note_chunk_embeddings
//   C2 – a structural reference edge (tier='mentions', client_tag NULL) written
//   C6 – projects/demo/_index.md regenerated by IndexNoteScheduler
//   D  – the regenerated _index.md is EXCLUDED from sync (no churn)
//
// Constructor signatures are mirrored from tests/server/ingest/ingest-flow.test.ts
// (Task 32, already green).
import { test, expect, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, rmSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Database } from "bun:sqlite";
import { initSchema } from "../../src/server/db";
import { FileManager } from "../../src/server/file-manager";
import { Indexer } from "../../src/server/indexer";
import { SectionsRepo } from "../../src/server/indexer/sections-repo";
import { MetadataRepo } from "../../src/server/indexer/metadata-repo";
import { ChunkEmbeddingsRepo } from "../../src/server/embeddings/chunks-repo";
import { EmbeddingService, type EngineLike } from "../../src/server/embeddings/service";
import { ProgressBus } from "../../src/server/embeddings/progress";
import { IndexNoteScheduler } from "../../src/server/ingest/index-note";
import { localHashes } from "../../src/server/sync/engine";

const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));

// FakeEngine: mirrors ingest-flow.test.ts exactly. Produces near-identical
// vectors so embeddings are written without requiring a model download.
const EMBED_MODEL = "Xenova/bge-small-en-v1.5";

class FakeEngine implements EngineLike {
  model = EMBED_MODEL;
  batchSize = 8;
  async embedBatch(texts: string[]): Promise<Float32Array[]> {
    return texts.map((_, i) => {
      const v = new Float32Array(4);
      v[0] = 1;
      v[1] = 0.9;
      v[i % 4] = 0.1;
      return v;
    });
  }
}

let vaultDir: string;
let db: Database;

beforeEach(() => {
  vaultDir = mkdtempSync(join(tmpdir(), "sync-recal-"));
  mkdirSync(join(vaultDir, ".scrypt"), { recursive: true });
  db = new Database(":memory:");
  initSchema(db);
});

afterEach(() => {
  db.close();
  rmSync(vaultDir, { recursive: true, force: true });
});

// Write the pulled bytes at the canonical create_note path — same layout the
// server uses after deps.local.createNote().
async function simulatePull(rel: string, raw: string, vaultRoot: string) {
  const abs = join(vaultRoot, rel);
  mkdirSync(join(abs, ".."), { recursive: true });
  await Bun.write(abs, raw);
}

test(
  "a pulled project note recalibrates: contextual embeddings + reference edge + refreshed _index.md, no sync churn",
  async () => {
    const scryptPath = join(vaultDir, ".scrypt");
    const fm = new FileManager(vaultDir, scryptPath);
    const sections = new SectionsRepo(db);
    const metadata = new MetadataRepo(db);
    const embeddings = new ChunkEmbeddingsRepo(db);
    const bus = new ProgressBus();
    const engine = new FakeEngine();

    // Real EmbeddingService options-object constructor (NOT positional).
    const embedService = new EmbeddingService({
      engine,
      repo: embeddings,
      bus,
      chunkOpts: { maxTokens: 450, overlapTokens: 50 },
    });

    // Indexer 3rd arg = Wave8Pipeline = { sections, embedService }.
    const indexer = new Indexer(db, fm, { sections, embedService });

    // Wire the scheduler so IndexNoteScheduler fires after reindexNote.
    const scheduler = new IndexNoteScheduler(
      { db, metadata, fm },
      { debounceMs: 15 },
    );
    const wrote: string[] = [];
    scheduler.onWrite = (p) => wrote.push(p);
    indexer.setIndexScheduler(scheduler);

    // ── SIMULATE A PULL ────────────────────────────────────────────────────
    // Write two project notes: source.md has a relative markdown link to
    // target.md (same directory sibling pattern used by real vaults).
    const sourceRaw = [
      "---",
      "title: Source Spec",
      "doc_type: spec",
      "project: demo",
      "---",
      "",
      "# Source Spec",
      "",
      "See [Target Doc](../research/target.md) for background context.",
      "",
      "## Plan",
      "",
      "The main plan body goes here.",
    ].join("\n");

    const targetRaw = [
      "---",
      "title: Target Doc",
      "doc_type: research",
      "project: demo",
      "---",
      "",
      "# Target Doc",
      "",
      "Background research content.",
    ].join("\n");

    await simulatePull("projects/demo/spec/source.md", sourceRaw, vaultDir);
    await simulatePull("projects/demo/research/target.md", targetRaw, vaultDir);

    // Two-pass reindex mirrors fullReindex's forward-ref resolution pattern:
    // first pass ensures both notes are in the DB (target first so source can
    // resolve the relative link on the second pass).
    await indexer.reindexNote("projects/demo/research/target.md");
    await indexer.reindexNote("projects/demo/spec/source.md");
    // Second pass on source resolves the relative link now that target is in DB.
    await indexer.reindexNote("projects/demo/spec/source.md");

    // Denormalize project + doc_type onto the notes rows. In the real pull flow
    // deps.local.createNote() calls the create_note MCP tool which reads
    // frontmatter and sets these columns; reindexNote alone does not (it only
    // updates title/content_hash/timestamps). We mirror the MCP tool's UPDATE
    // directly so collectProjectEntries(WHERE project=?) can find the notes.
    db.run(
      "UPDATE notes SET project = 'demo', doc_type = 'research' WHERE path = ?",
      ["projects/demo/research/target.md"],
    );
    db.run(
      "UPDATE notes SET project = 'demo', doc_type = 'spec' WHERE path = ?",
      ["projects/demo/spec/source.md"],
    );
    // Re-run the scheduler trigger now that project is set (the debounce timer
    // from reindexNote already fired but _index.md was generated with null
    // project — re-trigger by scheduling explicitly then waiting again).
    scheduler.schedule("demo");

    // Let the debounced per-project index settle (debounceMs=15 → wait 60ms).
    await wait(60);

    // ── (a) C1 — contextual embeddings ────────────────────────────────────
    // note_chunk_embeddings.chunk_text holds the RAW body (breadcrumb prefix
    // only feeds the model, is NOT persisted). Gated like reindexNote itself.
    if (process.env.SCRYPT_EMBED_DISABLE !== "1") {
      const chunks = db
        .query<{ chunk_text: string }, [string]>(
          "SELECT chunk_text FROM note_chunk_embeddings WHERE note_path = ?",
        )
        .all("projects/demo/spec/source.md");
      expect(chunks.length).toBeGreaterThan(0);
      // chunk_text holds the raw body paragraphs (headings are stripped by the
      // chunker; the breadcrumb prefix only feeds the model, not persisted).
      expect(
        chunks.some(
          (c) =>
            c.chunk_text.includes("main plan body") ||
            c.chunk_text.includes("Target Doc") ||
            c.chunk_text.includes("background"),
        ),
      ).toBe(true);
    }

    // ── (b) C2 — structural reference edge ────────────────────────────────
    // tier='mentions' for markdown-link-derived edges; client_tag is NULL
    // (distinguishes deterministic reference edges from AI-asserted ones).
    const edge = db
      .query<
        { tier: string; client_tag: string | null },
        [string, string]
      >(
        `SELECT tier, client_tag FROM graph_edges
         WHERE source = ? AND target = ?`,
      )
      .get(
        "projects/demo/spec/source.md",
        "projects/demo/research/target.md",
      );
    expect(edge?.tier).toBe("mentions");
    expect(edge?.client_tag).toBeNull();

    // ── (c) C6 — _index.md regenerated ───────────────────────────────────
    expect(wrote).toContain("demo");
    const index = await fm.readNote("projects/demo/_index.md");
    expect(index).not.toBeNull();
    expect(index!.content).toContain("Source Spec");
    expect(index!.content).toContain("Target Doc");

    // ── (d) No sync churn — _index.md excluded from localHashes ──────────
    // localHashes() already filters out any path ending in /_index.md so the
    // regenerated index file never appears as "needs push" in the sync engine.
    const hashes = await localHashes(fm);
    for (const path of hashes.keys()) {
      expect(path.endsWith("/_index.md")).toBe(false);
    }
    // The project note itself IS in the sync set (it came from the pull).
    expect(hashes.has("projects/demo/spec/source.md")).toBe(true);
  },
  120_000,
);
