// src/server/ingest/index-note.ts
//
// Deterministic per-project index note generator (C6). Rewrites
// projects/<project>/_index.md from DB facts. The file is fully generated —
// a header warns against hand edits and the whole body is overwritten on
// every run. Pure renderer (renderIndexNote) is split from the I/O collector
// (collectProjectEntries) and orchestrator (generateProjectIndex) so the
// markdown shaping is unit-testable.
import { stringifyFrontmatter } from "../parsers";
import type { DocType } from "../vocab/doc-types";
import type { Database } from "bun:sqlite";
import type { MetadataRepo } from "../indexer/metadata-repo";
import type { FileManager } from "../file-manager";
import {
  findSimilarPairs,
  getSimilarityThreshold,
} from "../graph/semantic-similarity";

export interface IndexNoteEntry {
  path: string;
  title: string;
  summary: string | null;
  doc_type: DocType | null;
  /** Display titles (or slugs) of top-N cosine neighbors — suggestions only. */
  related: string[];
  /** Meaningful edges (references + typed) involving this note. */
  links: { target: string; label: string }[];
}

export interface IndexGenDeps {
  db: Database;
  metadata: MetadataRepo;
  /** Embedding model id; defaults to the bge-small env default. */
  model?: string;
  /** Required by generateProjectIndex (Task 28) to write _index.md. */
  fm?: FileManager;
}

const GEN_HEADER =
  "<!-- GENERATED by Scrypt — do not edit. Regenerated on every ingest/reindex. -->";

/** Max cosine neighbors recorded as `related[]` hints per note. */
const MAX_RELATED_HINTS = 3;

/** Escape `[` / `]` so titles/labels can't break markdown link text. */
function mdEscape(s: string): string {
  return s.replace(/([\[\]])/g, "\\$1");
}

/** Path of an entry relative to its project root (drops projects/<project>/). */
function relWithinProject(project: string, path: string): string {
  const prefix = `projects/${project}/`;
  return path.startsWith(prefix) ? path.slice(prefix.length) : path;
}

function slugFromRel(rel: string): string {
  const file = rel.split("/").pop() ?? rel;
  return file.replace(/\.md$/, "");
}

export function renderIndexNote(
  project: string,
  entries: IndexNoteEntry[],
): string {
  const lines: string[] = [GEN_HEADER, ""];

  // Group by doc_type; "other" (null) bucket last, named groups sorted.
  const groups = new Map<string, IndexNoteEntry[]>();
  for (const e of entries) {
    const key = e.doc_type ?? "other";
    const arr = groups.get(key) ?? [];
    arr.push(e);
    groups.set(key, arr);
  }
  const groupKeys = [...groups.keys()].sort((a, b) => {
    if (a === "other") return 1;
    if (b === "other") return -1;
    return a.localeCompare(b);
  });

  for (const key of groupKeys) {
    lines.push(`## ${key}`, "");
    const bucket = groups
      .get(key)!
      .slice()
      .sort((a, b) => a.title.localeCompare(b.title));
    for (const e of bucket) {
      const rel = relWithinProject(project, e.path);
      const link = `- [${mdEscape(e.title)}](${rel})`;
      lines.push(e.summary ? `${link} — ${e.summary}` : link);
      if (e.related.length > 0) {
        lines.push(`  - related: ${e.related.join(", ")}`);
      }
    }
    lines.push("");
  }

  // Links section — only when at least one note has edges.
  const linked = entries.filter((e) => e.links.length > 0);
  if (linked.length > 0) {
    lines.push("## Links", "");
    for (const e of linked
      .slice()
      .sort((a, b) => a.title.localeCompare(b.title))) {
      const parts = e.links.map((l) => {
        const rel = relWithinProject(project, l.target);
        return `${mdEscape(l.label)} [${mdEscape(slugFromRel(rel))}](${rel})`;
      });
      lines.push(`- **${mdEscape(e.title)}** ${parts.join(", ")}`);
    }
    lines.push("");
  }

  const fm: Record<string, unknown> = {
    title: `${project} — index`,
    kind: "index",
    project,
    source: "scrypt",
  };
  return stringifyFrontmatter(fm, lines.join("\n").trimEnd() + "\n");
}

// ---------------------------------------------------------------------------
// DB helpers
// ---------------------------------------------------------------------------

function hasColumn(db: Database, table: string, col: string): boolean {
  const cols = db
    .query(`PRAGMA table_info(\`${table}\`)`)
    .all() as { name: string }[];
  return cols.some((c) => c.name === col);
}

interface NoteRow {
  path: string;
  title: string | null;
  doc_type: string | null;
}
interface EdgeRow {
  source: string;
  target: string;
  reason: string | null;
  rel_type: string | null;
}

/**
 * Build IndexNoteEntry[] for a project from DB facts. References + typed
 * edges become `links`; cosine neighbors (off-graph, C3) become `related`.
 */
export function collectProjectEntries(
  deps: IndexGenDeps,
  project: string,
): IndexNoteEntry[] {
  const model =
    deps.model ??
    process.env.SCRYPT_EMBED_MODEL ??
    "Xenova/bge-small-en-v1.5";
  const notes = deps.db
    .query<NoteRow, [string]>(
      `SELECT path, title, doc_type FROM notes WHERE project = ? ORDER BY path`,
    )
    .all(project)
    // The generated index itself is never listed inside its own ToC.
    .filter((n) => !n.path.endsWith("/_index.md"));

  const projectPaths = new Set(notes.map((n) => n.path));
  const relCol = hasColumn(deps.db, "graph_edges", "rel_type");
  const edgeSql = relCol
    ? `SELECT source, target, reason, rel_type FROM graph_edges
         WHERE (source = ? OR target = ?) AND tier != 'semantically_related'
         ORDER BY source, target`
    : `SELECT source, target, reason, NULL AS rel_type FROM graph_edges
         WHERE (source = ? OR target = ?) AND tier != 'semantically_related'
         ORDER BY source, target`;

  // Cosine neighbors: ONE batched call, restricted to this project's own
  // embedded notes. Keeps related[] hints within-project (consistent with
  // the snapshot's drop-cross-project-semantic rule) and makes the inner
  // dot-product loop O(project²) rather than O(vault²). NOT per-note.
  const projectEmbedded = deps.db
    .query<{ note_path: string }, [string]>(
      `SELECT DISTINCT note_path FROM note_chunk_embeddings WHERE model = ?
         ORDER BY note_path`,
    )
    .all(model)
    .map((r) => r.note_path)
    .filter((p) => projectPaths.has(p));
  const pairs =
    projectEmbedded.length >= 2
      ? findSimilarPairs(deps.db, projectEmbedded, model, {
          minSimilarity: getSimilarityThreshold(),
        })
      : [];
  const relatedOf = new Map<string, string[]>();
  for (const p of pairs) {
    for (const [self, other] of [
      [p.source, p.target],
      [p.target, p.source],
    ] as const) {
      if (!projectPaths.has(self)) continue;
      const arr = relatedOf.get(self) ?? [];
      if (arr.length < MAX_RELATED_HINTS) arr.push(slugFromRel(other));
      relatedOf.set(self, arr);
    }
  }

  return notes.map((n) => {
    const edges = deps.db
      .query<EdgeRow, [string, string]>(edgeSql)
      .all(n.path, n.path);
    const links = edges
      .filter((e) => e.source === n.path)
      .map((e) => ({
        target: e.target,
        label: e.rel_type ?? e.reason ?? "reference",
      }));
    return {
      path: n.path,
      title: n.title ?? slugFromRel(n.path),
      summary: deps.metadata.get(n.path)?.summary ?? null,
      doc_type: (n.doc_type as DocType | null) ?? null,
      related: relatedOf.get(n.path) ?? [],
      links,
    };
  });
}
