// src/cli/compose.ts
//
// PURE generator for docker-compose.override.yml. Compose auto-merges an
// override file; scalar fields (like `platform`) are REPLACED when specified.
// We set platform to the host arch so the committed arm64 pin can't break x64
// hosts, and we point the ingest mount at a real host path (the committed file's
// default is a macOS-only path).

export interface OverrideOpts {
  /** Absolute host path to mount read-only at /ingest for batch_ingest. */
  ingestDir: string;
  /** Host arch, e.g. "x64" | "arm64". Mapped to a linux/* platform. */
  arch: string;
}

function dockerPlatform(arch: string): string {
  if (arch === "arm64" || arch === "aarch64") return "linux/arm64";
  return "linux/amd64";
}

/** YAML-escape a scalar for a double-quoted value. */
function yamlStr(s: string): string {
  return '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

export function buildOverrideYaml(opts: OverrideOpts): string {
  const platform = dockerPlatform(opts.arch);
  return [
    "# Generated by `scrypt init` — local overrides for docker-compose.yml.",
    "# Safe to edit. Gitignored. Regenerate by re-running `scrypt init`.",
    "services:",
    "  scrypt:",
    `    platform: ${platform}`,
    "    volumes:",
    `      - ${yamlStr(opts.ingestDir)}:/ingest:ro`,
    "",
  ].join("\n");
}
